---
output: 
    bookdown::pdf_document2:
      toc: False
      number_sections: False
classoption: landscape

header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \pagenumbering{gobble}

---

```{r, setup, echo = FALSE, include=FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE)

library(tidyverse)
library(tab)
library(RcmdrMisc)
library(kableExtra)

```

```{r load_data, echo = FALSE}

# Load data
blanks <- read_csv("../data/raw_data/blanks.csv")
cores <- read_csv("../data/raw_data/cores.csv")

```


```{r all_blanks, echo = FALSE}

# Calculate Elongation/Flattening for blanks and tidy data (including lumping categories with little (5%) representation into 'Other')
blanks_tidy <- blanks %>%
  drop_na(Length, Width, Thickness) %>% 
  mutate(Elongation = Length / Width) %>%
  mutate(Flattening = Width / Thickness) %>%
  mutate(Profile = fct_lump(Profile, prop = 0.05)) %>%
  mutate(EdgeShape = fct_lump(EdgeShape, prop = 0.05)) %>%
  mutate(CrossSection = fct_lump(CrossSection, prop = 0.05)) %>%
  mutate(PlatformType = fct_lump(PlatformType, prop = 0.05)) %>%
  mutate(CortexLoc = fct_lump(CortexLoc, prop = 0.05)) %>%
  mutate(DorsalPattern = fct_lump(DorsalPattern, prop = 0.05)) %>%
  mutate(Termination = fct_lump(Termination, prop = 0.05)) %>%
  mutate(CortexPerc = dplyr::recode(CortexPerc, "75-95%" = "76-100%", "25-75%" ="26-75%", "100%" = "76-100%", "<25%" = "1-25%", ">95%" = "76-100%", "0%" = "0%")) #%>%
  #mutate(Sites = dplyr::recode(Context, "PAP 4'00-4'75" = "PAP", "PAP 4'75-5'25" ="PAP", "PAP 5'25-6'25" = "PAP", "AMB II" = "AMB", "AMB IV" = "AMB", "AMB VI" = "AMB",
                              # "VB A" = "VB", "VB B" = "VB", "VB C" = "VB", "VALM" = "VALM"))

# Convert ScarNumber to factor
blanks_tidy$ScarNumber <- factor(blanks_tidy$ScarNumber)

# Bin continous variables ("natural" is used to cut between bins to be determined by a k-means clustering)
blanks_tidy$ElongFact <- binVariable(blanks_tidy$Elongation, bins = 2, method = "natural", labels = c("low", "high"))
blanks_tidy$FlattFact <- binVariable(blanks_tidy$Flattening, bins = 2, method = "natural", labels = c("low", "high"))

```


## Table S1 - Blanks attribute frequency

```{r blanks_cross_table, echo=FALSE}

var_list <- c("PlatformType", "CrossSection", "Profile", "DorsalPattern", "EdgeShape", "CortexPerc", "Termination", "Elongation", "Flattening")

blanks_tidy <- as.data.frame(blanks_tidy)

blanks_table <- tabmulti(blanks_tidy, "Context", var_list,
                 p.include = FALSE,
                 n.headings = FALSE,
                 bold.varnames = TRUE,
                 bold.colnames = TRUE,
                 ynames = c(PlatformType = "Platform type", CrossSection = "Cross section", Profile = "Profile", DorsalPattern = "Dorsal pattern", EdgeShape = "Edge shape", CortexPerc = "Cortex %", Termination = "Termination", Elongation = "Elongation", Flattening = "Flattening")) 

blanks_table <- blanks_table %>% 
  as_tibble() %>% 
  select(" " = Variable, `AMB II`, `AMB IV`, `AMB VI`, `PAP 4'00-4'75`, `PAP 4'75-5'25`, `PAP 5'25-6'25`, `VALM`, `VB A`, `VB B`, `VB C`, Total = Overall)

knitr::kable(blanks_table, "latex", booktabs = TRUE) %>% 
  kable_styling(latex_options = c("scale_down"))

```

