---
output: 
    bookdown::pdf_document2:
      toc: False
      number_sections: False
classoption: landscape

header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \pagenumbering{gobble}

---

```{r, setup, echo = FALSE, include=FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE)

library(tidyverse)
library(tab)
library(RcmdrMisc)
library(kableExtra)

```

```{r load_data, echo = FALSE}

# Load data
blanks <- read_csv("../data/raw_data/blanks.csv")
cores <- read_csv("../data/raw_data/cores.csv")

```


```{r elongated, echo = FALSE}

# Calculate Elongation/Flattening for blanks and tidy data (including lumping categories with little (5%) representation into 'Other')
elongated_tidy <- blanks %>%
  filter(Class == "Elongated product") %>%
  drop_na(Length, Width, Thickness) %>%
  mutate(Elongation = Length / Width) %>%
  mutate(Flattening = Width / Thickness) %>%
  mutate(Profile = fct_lump(Profile, prop = 0.05)) %>%
  mutate(EdgeShape = fct_lump(EdgeShape, prop = 0.05)) %>%
  mutate(CrossSection = fct_lump(CrossSection, prop = 0.05)) %>%
  mutate(PlatformType = fct_lump(PlatformType, prop = 0.05)) %>%
  mutate(CortexLoc = fct_lump(CortexLoc, prop = 0.05)) %>%
  mutate(DorsalPattern = fct_lump(DorsalPattern, prop = 0.05)) %>%
  mutate(Termination = fct_lump(Termination, prop = 0.05)) %>%
  mutate(CortexPerc = dplyr::recode(CortexPerc, "75-95%" = "76-100%", "25-75%" ="26-75%", "100%" = "76-100%", "<25%" = "1-25%", ">95%" = "76-100%", "0%" = "0%")) %>%
  mutate(ScarNumber = as.factor(ScarNumber)) %>%
  mutate(DorsalPattern = dplyr::recode(DorsalPattern, "Unidentifiable" = "Other")) %>%
  mutate(ScarNumber = dplyr::recode(ScarNumber, "4" = "4 or more", "5" = "4 or more", "6" = "4 or more", "7" = "4 or more", "8" = "4 or more", "9" = "4 or more"))

# Convert ScarNumber to factor
elongated_tidy$ScarNumber <- factor(elongated_tidy$ScarNumber)

# Bin continous variables ("natural" is used to cut between bins to be determined by a k-means clustering)
elongated_tidy$ElongFact <- binVariable(elongated_tidy$Elongation, bins = 2, method = "natural", labels = c("low", "high"))
elongated_tidy$FlattFact <- binVariable(elongated_tidy$Flattening, bins = 2, method = "natural", labels = c("low", "high"))

```


## Table S2 - Elongated blanks attribute frequency

```{r elongated_cross_table, echo=FALSE}

var_list <- c("PlatformType", "CrossSection", "Profile", "DorsalPattern", "EdgeShape", "CortexPerc", "Termination", "Elongation", "Flattening")

elongated_tidy <- as.data.frame(elongated_tidy)

elongated_table <- tabmulti(elongated_tidy, "Context", var_list,
                 p.include = FALSE,
                 n.headings = FALSE,
                 bold.varnames = TRUE,
                 bold.colnames = TRUE,
                 ynames = c(PlatformType = "Platform type", CrossSection = "Cross section", Profile = "Profile", DorsalPattern = "Dorsal pattern", EdgeShape = "Edge shape", CortexPerc = "Cortex %", Termination = "Termination", Elongation = "Elongation", Flattening = "Flattening")) 

elongated_table <- elongated_table %>% 
  as_tibble() %>% 
  select(" " = Variable, `AMB II`, `AMB IV`, `AMB VI`, `PAP 4'00-4'75`, `PAP 4'75-5'25`, `PAP 5'25-6'25`, `VALM`, `VB A`, `VB B`, `VB C`, Total = Overall)

knitr::kable(elongated_table, "latex", booktabs = TRUE) %>% 
  kable_styling(latex_options = c("scale_down"))

```
